# Generated by Django 4.0 on 2022-06-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_reservation_guest_alter_reservation_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
    ]
